alarm/alarm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('photo.urls', namespace='photos'))
]

alarm/photo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views
urlpatterns = [
    url('^$', views.DayView.as_view(), name='day'),
    url('^photos/(?P<day>.*)/(?P<page>\d+)$', views.PhotosView.as_view(), name='photos'),
    url('^photo/(?P<image_id>\w+)', views.PhotoView.as_view(), name='photo'),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alarm/photo/models.py
from django.db import models

# Create your models here.
class Photo(models.Model):
    create_time = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images', verbose_name='入侵人员照片')
    class Meta:
            verbose_name = '照片'
            verbose_name_plural = verbose_name
    def __str__(self):
        return str(self.create_time)

alarm/photo/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.generic import View
from photo.models import Photo
import time, datetime
from django.core.paginator import Paginator
# Create your views here.


class DayView(View):
    def get(self, request):
        all_photos_days = Photo.objects.all()
        photos_day = []
        photos_days = []
        for photo_day in all_photos_days:
            time = str(photo_day.create_time).split(' ')[0]
            photos_day.append(time)
            photos_day = list(set(photos_day))

        for day in photos_day:
            photo_create_time = Photo.objects.filter(create_time__startswith=day)[0]
            photo_create_time.day = day
            photos_days.append(photo_create_time)
        context = {'photos_days': photos_days}
        return render(request, 'day.html', context)

    def post(self, request):
        create_time = request.POST.get('create_time', '1')
        photo_name = request.POST.get('photo_name', '1')
        photo = Photo()
        photo.create_time = create_time
        photo.image = photo_name
        photo.save()
        print (create_time, photo_name)
        return JsonResponse({"res":1, "message":"chenggong"})
class PhotosView(View):
    def get(self, request, day, page):
        create_time = time.strftime('%Y-%m-%d', time.localtime())
        all_photos = Photo.objects.filter(create_time__startswith=day).order_by('-create_time')
        # all_photos = Photo.objects.filter(create_time__gt=datetime.date(2019,3,7)).order_by('-create_time')
        for photos in all_photos:
            image_id = (str(photos.image)).split('/')[-1]
            photos.image_id = image_id
            print(photos.image)

        paginator = Paginator(all_photos, 5)
        try:
            page = int(page)
        except Exception as e:
            page = 1
        if page > paginator.num_pages:
            page = paginator.num_pages
        photos = paginator.page(page)
        num_pages = paginator.num_pages
        if num_pages < 5:
            pages = range(1, num_pages + 1)
        elif page <= 3:
            pages = range(1, 6)
        elif num_pages - page <= 2:
            pages = range(num_pages - 4, num_pages + 1)
        else:
            pages = range(page - 2, page + 3)


        context = {'all_photos': all_photos,
                   'day': day,
                   'photos': photos,
                   'pages': pages}
        return render(request, 'photos.html', context=context)


class  PhotoView(View):
    def get(self, request, image_id):
        image_id = 'group1/M00/00/00/'+image_id
        image = Photo.objects.get(image=image_id)
        content = {'image': image}
        print(content)
        return render(request, 'photos.html')

alarm/templates/day.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>照片合集</title>
    <style type="text/css">
        .photo{''}
    </style>
</head>
<body>
{% for photo_day in photos_days %}
<div class="photo"><a href="{% url 'photos:photos' photo_day.day 1 %}" class="photo"><img src="data:image/jpg;base64,{{ photo_day.image }}">{{ photo_day.day }}</a></div>
{% endfor %}
</body>
</html>

alarm/templates/photos.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello word</title>

</head>
<body>
    {% for photo in photos %}
	<div class="photo"><a href="{% url 'photos:photo' photo.image_id %}"><img src="{% static 'Image/' %}{{ photo.image }}"></a></div>
	<p>{{ photo.create_time }}</p>
    {% endfor %}
<div class="pagenation">
				{% if photos.has_previous %}
				<a href="{% url 'photos:photos' day photos.previous_page_number %}"><上一页</a>
				{% endif %}
				{% for page_index in pages %}
				{% if page_index == skus_page.number %}
				<a href="{% url 'photos:photos' day page_index %}" class="active">{{ page_index }}</a>
				{% else %}
				<a href="{% url 'photos:photos' day page_index %}">{{ page_index }}</a>
				{% endif %}
				{% endfor %}
				{% if photos.has_next %}
				<a href="{% url 'photos:photos' day photos.next_page_number %}">下一页></a>
				{% endif %}
			</div>
</body>
</html>